### ISSUE TITLE
Install MariaDB

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/school#18]

**Comment by ng-druid** [comment]
Certainly! Below is an example of how you can structure an Ansible role to install MariaDB, separating the tasks into separate files where it makes sense. The role will be located in

`roles/mariadb`

.

### Directory Structure

`roles/ └── mariadb/
    ├── defaults/
    │   └── main.yml
    ├── tasks/
    │   ├── install.yml
    │   ├── configure.yml
    │   ├── secure_installation.yml
    │   └── main.yml
    ├── handlers/
    │   └── main.yml
    ├── templates/
    │   └── my.cnf.j2
    ├── vars/
    │   └── main.yml
    └── meta/
        └── main.yml` 

----------

### 1.

`defaults/main.yml`

This file contains default variables for the role.

`mariadb_root_password:  "default_root_password"  mariadb_databases:  []  mariadb_users:  []` 

----------

### 2.

`vars/main.yml`

This file is optional and contains static variables. You can leave it empty for now.

`# Empty or add static variables here if needed` 

----------

### 3.

`tasks/install.yml`

This file contains tasks for installing MariaDB.

`-  name: Install MariaDB package  ansible.builtin.yum:   name: mariadb-server
  state: present 
-  name: Ensure MariaDB service is enabled and started  ansible.builtin.service:   name: mariadb  state: started  enabled:  true` 

----------

### 4.

`tasks/configure.yml`

This file contains tasks for configuring MariaDB.

`-  name: Copy MariaDB configuration file  ansible.builtin.template:   src: my.cnf.j2  dest: /etc/my.cnf  owner: root  group: root  mode:  '0644'   notify: Restart MariaDB` 

----------

### 5.

`tasks/secure_installation.yml`

This file contains tasks for securing the MariaDB installation.

`-  name: Secure MariaDB installation - Set root password  ansible.builtin.mysql_user:   name: root  host: localhost  password:  "{{ mariadb_root_password }}"   check_implicit_admin:  true  
-  name: Remove anonymous users  ansible.builtin.mysql_user:   name:  ''   host_all:  true   state: absent 
-  name: Remove test database  ansible.builtin.mysql_db:   name: test  state: absent 
-  name: Reload privilege tables  ansible.builtin.mysql_user:   name: root  host: localhost  password:  "{{ mariadb_root_password }}"   priv:  "*.*:ALL,GRANT"   state: present  check_implicit_admin:  true` 

----------

### 6.

`tasks/main.yml`

This file includes all the other task files.

`-  import_tasks: install.yml -  import_tasks: configure.yml -  import_tasks: secure_installation.yml` 

----------

### 7.

`handlers/main.yml`

This file defines handlers for the role.

`-  name: Restart MariaDB  ansible.builtin.service:   name: mariadb  state: restarted` 

----------

### 8.

`templates/my.cnf.j2`

This is a Jinja2 template for the MariaDB configuration file.

`[mysqld]  bind-address  =  0.0.0.0  datadir  =  /var/lib/mysql  socket  =  /var/lib/mysql/mysql.sock  
[mysqld_safe]  log-error  =  /var/log/m` 

AI-generated content may be incorrect

install on debian/ubuntu

To install MariaDB on Debian/Ubuntu using Ansible, you need to adjust the playbook slightly because the package manager and repository setup differ from CentOS/RedHat-based systems. Below is the updated role for Debian/Ubuntu systems.

### Updated Directory Structure

`roles/ └── mariadb/
    ├── defaults/
    │   └── main.yml
    ├── tasks/
    │   ├── install.yml
    │   ├── configure.yml
    │   ├── secure_installation.yml
    │   └── main.yml
    ├── handlers/
    │   └── main.yml
    ├── templates/
    │   └── my.cnf.j2
    ├── vars/
    │   └── main.yml
    └── meta/
        └── main.yml` 

----------

### 1.

`defaults/main.yml`

This file contains default variables for the role.

`mariadb_root_password:  "default_root_password"  mariadb_databases:  []  mariadb_users:  []  mariadb_version:  "10.6"  # You can change this to your preferred version.` 

----------

### 2.

`tasks/install.yml`

This file installs the MariaDB server on Debian/Ubuntu systems.

`-  name: Add MariaDB APT repository  ansible.builtin.apt_repository:   repo: deb [arch=amd64,arm64,ppc64el] http://mirror.mariadb.org/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main  state: present  update_cache: yes 
-  name: Install MariaDB server package  ansible.builtin.apt:   name: mariadb-server
  state: present  update_cache: yes 
-  name: Ensure MariaDB service is enabled and started  ansible.builtin.service:   name: mariadb  state: started  enabled:  true` 

----------

### 3.

`tasks/configure.yml`

This file configures the MariaDB server.

`-  name: Copy MariaDB configuration file  ansible.builtin.template:   src: my.cnf.j2  dest: /etc/mysql/my.cnf  owner: root  group: root  mode:  '0644'   notify: Restart MariaDB` 

----------

### 4.

`tasks/secure_installation.yml`

This file secures the MariaDB installation.

`-  name: Secure MariaDB installation - Set root password  ansible.builtin.mysql_user:   name: root  host: localhost  password:  "{{ mariadb_root_password }}"   check_implicit_admin:  true  
-  name: Remove anonymous users  ansible.builtin.mysql_user:   name:  ''   host_all:  true   state: absent 
-  name: Remove test database  ansible.builtin.mysql_db:   name: test  state: absent 
-  name: Reload privilege tables  ansible.builtin.mysql_user:   name: root  host: localhost  password:  "{{ mariadb_root_password }}"   priv:  "*.*:ALL,GRANT"   state: present  check_implicit_admin:  true` 

----------

### 5.

`tasks/main.yml`

This file includes all the task files.

`-  import_tasks: install.yml -  import_tasks: configure.yml -  import_tasks: secure_installation.yml` 

----------

### 6.

`handlers/main.yml`

This file defines handlers for the role.

`-  name: Restart MariaDB  ansible.builtin.service:   name: mariadb  state: restarted` 

----------

### 7. `templates/my.cnf.j2

AI-generated content may be incorrect

continue

Certainly! Here's the continuation of the

`templates/my.cnf.j2`

file, which is the MariaDB configuration template:

----------

### 7.

`templates/my.cnf.j2`

This is a Jinja2 template for the MariaDB configuration file, customized for Debian/Ubuntu systems. You can modify the template based on your specific requirements.

`[mysqld]  bind-address  =  0.0.0.0  datadir  =  /var/lib/mysql  socket  =  /var/run/mysqld/mysqld.sock  log_error  =  /var/log/mysql/error.log  
# Performance tuning options  max_connections  =  100  query_cache_size  =  16M  query_cache_type  =  1  
[mysqld_safe]  log_error  =  /var/log/mysql/error.log  pid_file  =  /var/run/mysqld/mysqld.pid  
[client]  port  =  3306  socket  =  /var/run/mysqld/mysqld.sock  
[mysqldump]  quick
quote-names
max_allowed_packet  =  16M  
[mysql]  no_auto_rehash

[isamchk]  key_buffer_size  =  16M` 

----------

### 8.

`meta/main.yml`

This file contains metadata about the role, such as dependencies.

`galaxy_info:   role_name: mariadb  author: your_name  description: Install and configure MariaDB on Debian/Ubuntu systems.  company: your_company  license: MIT  min_ansible_version:  2.9   platforms:   -  name: Debian  versions:   - buster  - bullseye  -  name: Ubuntu  versions:   - focal  - jammy  categories:   - database  - sql 
dependencies:  []` 

----------

### Example Playbook to Use the Role

Now that the

`mariadb`

role is fully defined, you can use it in an Ansible playbook like this:

`-  name: Install and configure MariaDB  hosts: database_servers  become: yes  roles:   - mariadb` 

----------

### Testing the Role

To test the role, ensure that your inventory file specifies the

`database_servers`

group or another target group containing the relevant hosts.

Example

`inventory.yml`

:

`all:   children:   database_servers:   hosts:   db1.example.com:   db2.example.com:` 

----------

### Notes on Customization

1.  **MariaDB Version**: In
    
    `defaults/main.yml`
    
    , you can specify the version of MariaDB you want to install. For example,
    
    `10.6`
    
    ,
    
    `10.5`
    
    , etc.
2.  **Database Creation**: If you want to create databases or users automatically, you can extend the role to include tasks for creating databases and users using the
    
    `mariadb_databases`
    
    and
    
    `mariadb_users`
    
    variables.
3.  **Firewall Rules**: Ensure that the MariaDB port (
    
    `3306`
    
    ) is open in your firewall if you plan to access it remotely.

Let me know if you need additional features or explanations!

**Comment by ng-druid** [comment]
```yaml
- name: Copy MariaDB configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MariaDB
```

**Comment by ng-druid** [comment]
```yaml
- name: Secure MariaDB installation - Set root password
  ansible.builtin.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    check_implicit_admin: true

- name: Remove anonymous users
  ansible.builtin.mysql_user:
    name: ''
    host_all: true
    state: absent

- name: Remove test database
  ansible.builtin.mysql_db:
    name: test
    state: absent

- name: Reload privilege tables
  ansible.builtin.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    check_implicit_admin: true
```

**Comment by ng-druid** [comment]
- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: secure_installation.yml

**Comment by ng-druid** [comment]
```yaml
galaxy_info:
  role_name: mariadb
  author: your_name
  description: Install and configure MariaDB on Debian/Ubuntu systems.
  company: your_company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  categories:
    - database
    - sql

dependencies: []
```
