### ISSUE TITLE
Fixing pi5 bazel

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/school#23]
Fixing the bazel key:

```bash
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://bazel.build/bazel-release.pub.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/bazel-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/bazel-keyring.gpg] https://storage.googleapis.com/bazel-apt stable main" | sudo tee /etc/apt/sources.list.d/bazel.list
sudo apt update
```

**Comment by ng-druid** [comment]
**********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "E:Conflicting values set for option Signed-By regarding source https://storage.googleapis.com/bazel-apt/ stable: /etc/apt/keyrings/bazel-keyring.gpg != , E:The list of sources could not be read."}

**Comment by ng-druid** [comment]
```bash
ls -l /etc/apt/keyrings/bazel-keyring.gpg
sudo chmod 644 /etc/apt/keyrings/bazel-keyring.gpg
sudo apt-get clean
sudo apt update
```

**Comment by ng-druid** [comment]
```bash
grep -r "storage.googleapis.com/bazel-apt" /etc/apt/sources.list /etc/apt/sources.list.d/
```

**Comment by ng-druid** [comment]
```bash
ls -l /etc/apt/keyrings/bazel-keyring.gpg
```

**Comment by ng-druid** [comment]
However, still have an issue with it not being able to find the bazel apt repo even through the key is properly added.

```bash
---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - gnupg
      - curl
    state: present
    update_cache: yes

- name: Download and install Bazel GPG key
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present

- name: Add Bazel APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8"
    state: present

- name: Install Bazel
  apt:
    name: bazel-apt
    state: present
```

**Comment by ng-druid** [comment]
install deps:

```yaml
# tasks/install_dependencies.yml
---

- name: Install dependencies required to build Bazel from source
  apt:
    name:
      - g++
      - unzip
      - zip
      - python3
      - git
      - openjdk-11-jdk
      - curl
    state: present
    update_cache: yes
``
```

**Comment by ng-druid** [comment]
clone repo

```yaml
# tasks/clone_bazel_repo.yml
---

- name: Clone Bazel source repository
  git:
    repo: "{{ bazel_git_repo }}"
    dest: "{{ bazel_dest_dir }}"
    update: yes
```

**Comment by ng-druid** [comment]
build bazel

```yml
# tasks/build_bazel.yml
---

- name: Compile Bazel from source
  command: ./compile.sh
  args:
    chdir: "{{ bazel_dest_dir }}"

```

**Comment by ng-druid** [comment]
install bazel

```yml
# tasks/install_bazel.yml
---

- name: Install Bazel binary compiled from source
  copy:
    src: "{{ bazel_dest_dir }}/output/bazel"
    dest: "{{ bazel_binary_path }}"
    mode: '0755'
```

**Comment by ng-druid** [comment]
verify bazel

```yml
# tasks/verify_bazel.yml
---

- name: Verify Bazel installation from source
  command: "{{ bazel_binary_path }} --version"
  register: bazel_version_output

- name: Output installed Bazel version
  debug:
    msg: "Bazel built from source and installed successfully. Version: {{ bazel_version_output.stdout }}"

```

**Comment by ng-druid** [comment]
defaults

```yaml
# defaults/main.yml
bazel_version: "6.3.0"  # Version of Bazel to build
bazel_git_repo: "https://github.com/bazelbuild/bazel.git"  # Bazel Git repository
bazel_dest_dir: "/tmp/bazel"  # Directory where Bazel source code will be cloned
bazel_binary_path: "/usr/local/bin/bazel"  # Path to install the Bazel binary
```

**Comment by ng-druid** [comment]
tasks main

```yaml
# tasks/main.yml
---
# Main task file for building Bazel from source

- name: Install dependencies required to build Bazel from source
  import_tasks: install_dependencies.yml

- name: Clone Bazel source repository
  import_tasks: clone_bazel_repo.yml

- name: Checkout Bazel source code for the specified version
  import_tasks: checkout_bazel_version.yml

- name: Compile Bazel from source
  import_tasks: build_bazel.yml

- name: Install Bazel binary compiled from source
  import_tasks: install_bazel.yml

- name: Verify Bazel installation
  import_tasks: verify_bazel.yml
```

**Comment by ng-druid** [comment]
```bash
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["./compile.sh"], "delta": "0:00:00.048434", "end": "2025-06-03 18:12:50.681339", "msg": "non-zero return code", "rc": 1, "start": "2025-06-03 18:12:50.632905", "stderr": "readlink: missing operand\nTry 'readlink --help' for more information.\nBuilding Bazel from scratchfind: ‘/usr/share/java/netty-buffer.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-dns.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-haproxy.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-http2.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-http.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-memcache.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-mqtt.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-redis.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-smtp.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-socks.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-codec-stomp.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-common.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-handler.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-handler-proxy.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-resolver-dns.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-resolver-dns-native-macos.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-resolver.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-transport.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-transport-native-epoll.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-transport-native-kqueue.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-transport-native-unix-common.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-transport-sctp.jar’: No such file or directory\nfind: ‘/usr/share/java/gson.jar’: No such file or directory\nfind: ‘/usr/share/java/tomcat9-annotations-api.jar’: No such file or directory\nfind: ‘/usr/share/java/tomcat9-annotations-api.jar’: No such file or directory\nfind: ‘/usr/share/java/java-allocation-instrumenter.jar’: No such file or directory\nfind: ‘/usr/share/java/protobuf.jar’: No such file or directory\nfind: ‘/usr/share/java/protobuf-util.jar’: No such file or directory\nfind: ‘/usr/share/java/protobuf.jar’: No such file or directory\nfind: ‘/usr/share/java/protobuf-util.jar’: No such file or directory\nfind: ‘/usr/share/java/commons-lang.jar’: No such file or directory\nfind: ‘/usr/share/java/commons-compress.jar’: No such file or directory\nfind: ‘/usr/share/java/commons-pool2.jar’: No such file or directory\nfind: ‘/usr/share/java/velocity.jar’: No such file or directory\nfind: ‘/usr/share/java/asm.jar’: No such file or directory\nfind: ‘/usr/share/java/jackson-core.jar’: No such file or directory\nfind: ‘/usr/share/java/jcip-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/jcip-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/jsr305.jar’: No such file or directory\nfind: ‘/usr/share/java/jsr305.jar’: No such file or directory\nfind: ‘/usr/share/java/netty-tcnative.jar’: No such file or directory\nfind: ‘/usr/share/java/javapoet.jar’: No such file or directory\nfind: ‘/usr/share/java/jaxb-api.jar’: No such file or directory\nfind: ‘/usr/share/java/xz.jar’: No such file or directory\nfind: ‘/usr/share/java/geronimo-annotation-1.3-spec.jar’: No such file or directory\nfind: ‘/usr/share/java/com.android.tools.common.jar’: No such file or directory\nfind: ‘/usr/share/java/com.android.tools.repository.jar’: No such file or directory\nfind: ‘/usr/share/java/com.android.tools.layoutlib.layoutlib-api.jar’: No such file or directory\nfind: ‘/usr/share/java/guava.jar’: No such file or directory\nfind: ‘/usr/share/java/guava.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.report.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.report.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory\nfind: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-common.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-service.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-service-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/escapevelocity.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-value.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-value-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-common.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-value.jar’: No such file or directory\nfind: ‘/usr/share/java/auto-value-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/escapevelocity.jar’: No such file or directory\nfind: ‘/usr/share/java/javapoet.jar’: No such file or directory\nfind: ‘/usr/share/java/google-api-client.jar’: No such file or directory\nfind: ‘/usr/share/java/google-api-client-jackson2.jar’: No such file or directory\nfind: ‘/usr/share/java/google-http-client.jar’: No such file or directory\nfind: ‘/usr/share/java/google-http-client-jackson2.jar’: No such file or directory\nfind: ‘/usr/share/java/google-auth-library-oauth2-http.jar’: No such file or directory\nfind: ‘/usr/share/java/google-auth-library-credentials.jar’: No such file or directory\nfind: ‘/usr/share/java/error-prone-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/error-prone-type-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/error-prone-annotations.jar’: No such file or directory\nfind: ‘/usr/share/java/java-diff-utils.jar’: No such file or directory\nfind: ‘/usr/share/java/opencensus-api.jar’: No such file or directory\nfind: ‘/usr/share/java/opencensus-contrib-grpc-metrics.jar’: No such file or directory\nfind: ‘/usr/share/java/perfmark-api.jar’: No such file or directory\nfind: ‘/usr/share/java/flogger.jar’: No such file or directory\nfind: ‘/usr/share/java/flogger-system-backend.jar’: No such file or directory\nfind: ‘/usr/share/java/google-extensions.jar’: No such file or directory\nfind: ‘/usr/share/java/flogger.jar’: No such file or directory\nfind: ‘/usr/share/java/flogger-system-backend.jar’: No such file or directory\nfind: ‘/usr/share/java/google-extensions.jar’: No such file or directory\nfind: ‘/usr/share/java/checker-qual.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-api.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-auth.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-context.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-core.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-netty.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-protobuf.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-protobuf-lite.jar’: No such file or directory\nfind: ‘/usr/share/java/grpc-stub.jar’: No such file or directory\nfind: ‘/usr/share/java/hamcrest-core.jar’: No such file or directory\nfind: ‘/usr/share/java/junit4.jar’: No such file or directory\nfind: ‘/usr/share/java/reactive-streams.jar’: No such file or directory\nfind: ‘/usr/share/java/rxjava.jar’: No such file or directory\nfind: ‘/usr/share/java/caffeine.jar’: No such file or directory\n\nERROR: JDK not found, please set $JAVA_HOME.", "stderr_lines": ["readlink: missing operand", "Try 'readlink --help' for more information.", "Building Bazel from scratchfind: ‘/usr/share/java/netty-buffer.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-dns.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-haproxy.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-http2.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-http.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-memcache.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-mqtt.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-redis.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-smtp.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-socks.jar’: No such file or directory", "find: ‘/usr/share/java/netty-codec-stomp.jar’: No such file or directory", "find: ‘/usr/share/java/netty-common.jar’: No such file or directory", "find: ‘/usr/share/java/netty-handler.jar’: No such file or directory", "find: ‘/usr/share/java/netty-handler-proxy.jar’: No such file or directory", "find: ‘/usr/share/java/netty-resolver-dns.jar’: No such file or directory", "find: ‘/usr/share/java/netty-resolver-dns-native-macos.jar’: No such file or directory", "find: ‘/usr/share/java/netty-resolver.jar’: No such file or directory", "find: ‘/usr/share/java/netty-transport.jar’: No such file or directory", "find: ‘/usr/share/java/netty-transport-native-epoll.jar’: No such file or directory", "find: ‘/usr/share/java/netty-transport-native-kqueue.jar’: No such file or directory", "find: ‘/usr/share/java/netty-transport-native-unix-common.jar’: No such file or directory", "find: ‘/usr/share/java/netty-transport-sctp.jar’: No such file or directory", "find: ‘/usr/share/java/gson.jar’: No such file or directory", "find: ‘/usr/share/java/tomcat9-annotations-api.jar’: No such file or directory", "find: ‘/usr/share/java/tomcat9-annotations-api.jar’: No such file or directory", "find: ‘/usr/share/java/java-allocation-instrumenter.jar’: No such file or directory", "find: ‘/usr/share/java/protobuf.jar’: No such file or directory", "find: ‘/usr/share/java/protobuf-util.jar’: No such file or directory", "find: ‘/usr/share/java/protobuf.jar’: No such file or directory", "find: ‘/usr/share/java/protobuf-util.jar’: No such file or directory", "find: ‘/usr/share/java/commons-lang.jar’: No such file or directory", "find: ‘/usr/share/java/commons-compress.jar’: No such file or directory", "find: ‘/usr/share/java/commons-pool2.jar’: No such file or directory", "find: ‘/usr/share/java/velocity.jar’: No such file or directory", "find: ‘/usr/share/java/asm.jar’: No such file or directory", "find: ‘/usr/share/java/jackson-core.jar’: No such file or directory", "find: ‘/usr/share/java/jcip-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/jcip-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/jsr305.jar’: No such file or directory", "find: ‘/usr/share/java/jsr305.jar’: No such file or directory", "find: ‘/usr/share/java/netty-tcnative.jar’: No such file or directory", "find: ‘/usr/share/java/javapoet.jar’: No such file or directory", "find: ‘/usr/share/java/jaxb-api.jar’: No such file or directory", "find: ‘/usr/share/java/xz.jar’: No such file or directory", "find: ‘/usr/share/java/geronimo-annotation-1.3-spec.jar’: No such file or directory", "find: ‘/usr/share/java/com.android.tools.common.jar’: No such file or directory", "find: ‘/usr/share/java/com.android.tools.repository.jar’: No such file or directory", "find: ‘/usr/share/java/com.android.tools.layoutlib.layoutlib-api.jar’: No such file or directory", "find: ‘/usr/share/java/guava.jar’: No such file or directory", "find: ‘/usr/share/java/guava.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.report.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.report.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory", "find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory", "find: ‘/usr/share/java/auto-common.jar’: No such file or directory", "find: ‘/usr/share/java/auto-service.jar’: No such file or directory", "find: ‘/usr/share/java/auto-service-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/escapevelocity.jar’: No such file or directory", "find: ‘/usr/share/java/auto-value.jar’: No such file or directory", "find: ‘/usr/share/java/auto-value-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/auto-common.jar’: No such file or directory", "find: ‘/usr/share/java/auto-value.jar’: No such file or directory", "find: ‘/usr/share/java/auto-value-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/escapevelocity.jar’: No such file or directory", "find: ‘/usr/share/java/javapoet.jar’: No such file or directory", "find: ‘/usr/share/java/google-api-client.jar’: No such file or directory", "find: ‘/usr/share/java/google-api-client-jackson2.jar’: No such file or directory", "find: ‘/usr/share/java/google-http-client.jar’: No such file or directory", "find: ‘/usr/share/java/google-http-client-jackson2.jar’: No such file or directory", "find: ‘/usr/share/java/google-auth-library-oauth2-http.jar’: No such file or directory", "find: ‘/usr/share/java/google-auth-library-credentials.jar’: No such file or directory", "find: ‘/usr/share/java/error-prone-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/error-prone-type-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/error-prone-annotations.jar’: No such file or directory", "find: ‘/usr/share/java/java-diff-utils.jar’: No such file or directory", "find: ‘/usr/share/java/opencensus-api.jar’: No such file or directory", "find: ‘/usr/share/java/opencensus-contrib-grpc-metrics.jar’: No such file or directory", "find: ‘/usr/share/java/perfmark-api.jar’: No such file or directory", "find: ‘/usr/share/java/flogger.jar’: No such file or directory", "find: ‘/usr/share/java/flogger-system-backend.jar’: No such file or directory", "find: ‘/usr/share/java/google-extensions.jar’: No such file or directory", "find: ‘/usr/share/java/flogger.jar’: No such file or directory", "find: ‘/usr/share/java/flogger-system-backend.jar’: No such file or directory", "find: ‘/usr/share/java/google-extensions.jar’: No such file or directory", "find: ‘/usr/share/java/checker-qual.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-api.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-auth.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-context.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-core.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-netty.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-protobuf.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-protobuf-lite.jar’: No such file or directory", "find: ‘/usr/share/java/grpc-stub.jar’: No such file or directory", "find: ‘/usr/share/java/hamcrest-core.jar’: No such file or directory", "find: ‘/usr/share/java/junit4.jar’: No such file or directory", "find: ‘/usr/share/java/reactive-streams.jar’: No such file or directory", "find: ‘/usr/share/java/rxjava.jar’: No such file or directory", "find: ‘/usr/share/java/caffeine.jar’: No such file or directory", "", "ERROR: JDK not found, please set $JAVA_HOME."], "stdout": "", "stdout_lines": []}
```

**Comment by ng-druid** [comment]
-", "NOTE: This failure is likely occurring if you are trying to bootstrap bazel from", "a developer checkout. Those checkouts do not include the generated output of", "the protoc compiler (as we prefer not to version generated files).", "", "* To build a developer version of bazel, do", "", "    bazel build //src:bazel", "", "* To bootstrap your first bazel binary, please download a dist archive from our", "  release page at https://github.com/bazelbuild/bazel/releases and run", "  compile.sh on the unpacked archive.", "", "The full install instructions to install a release version of bazel can be found", "at https://bazel.build/install/compile-source", "For a rationale, why the bootstrap process is organized in this way, see", "https://bazel.build/designs/2016/10/11/distribution-artifact.html", "--------------------------------------------------------------------------------"], "stdout": "", "stdout_lines": []}

**Comment by ng-druid** [comment]
```yaml
# tasks/install_dependencies.yml
---

- name: Install required dependencies for Bazel build
  apt:
    name:
      - g++
      - unzip
      - zip
      - python3
      - git
      - openjdk-11-jdk
      - libprotobuf-java
      - libgson-java
      - libnetty-java
      - libcommons-lang3-java
      - libcommons-compress-java
      - libvelocity-java
      - libasm-java
      - libjackson-core-java
      - libxz-java
      - libguava-java
    state: present
    update_cache: yes

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    line: "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64"
    state: present

- name: Reload environment variables
  shell: source /etc/environment
```
