### ISSUE TITLE
nvm on all machines

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/school#24]
```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by ng-druid** [comment]
```yaml
ansible-role-nvm/
├── defaults/
│   └── main.yml
├── tasks/
│   ├── install_nvm.yml
│   ├── install_node.yml
│   └── main.yml
├── handlers/
│   └── main.yml
├── meta/
│   └── main.yml
├── README.md
├── vars/
│   └── main.yml
└── templates/
```

**Comment by ng-druid** [comment]
```yaml
# tasks/install_dependencies.yml
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - build-essential
      - libssl-dev
    state: present


```

**Comment by ng-druid** [comment]
```yaml
# tasks/install_nvm.yml
- name: Download NVM installation script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    dest: "/tmp/install_nvm.sh"
    mode: '0755'

- name: Run NVM installation script
  ansible.builtin.shell: bash /tmp/install_nvm.sh
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ nvm_directory }}"

- name: Set NVM environment variables system-wide
  ansible.builtin.copy:
    content: |
      export NVM_DIR="{{ nvm_directory }}"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    dest: /etc/profile.d/nvm.sh
    mode: '0755'
```
