### ISSUE TITLE
Install Docker

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/school#27]

**Comment by classifieds-dev** [comment]
Here's a response to your request for an Ansible playbook to install Docker on Pop!_OS. The playbook is designed to divide the tasks into separate files for better organization, following best practices.

---

To install Docker on Pop!_OS using Ansible, we can create a playbook structure with tasks organized into separate task files. Here's how you can structure it:

### Directory Structure
```plaintext
install_docker_playbook/
├── ansible.cfg
├── inventory
├── install_docker.yml
├── tasks/
│   ├── prerequisites.yml
│   ├── install_docker.yml
│   ├── start_services.yml
│   ├── post_install.yml
└── group_vars/
    └── all.yml
```

### 1. `ansible.cfg`
An optional configuration file for Ansible to set defaults:
```ini
[defaults]
inventory = inventory
host_key_checking = False
retry_files_enabled = False
```

### 2. `inventory`
Define the target Pop!_OS system(s):
```ini
[pop_os]
popos_host ansible_host=192.168.56.101 ansible_user=<your_user>
```

Replace `<your_user>` and `ansible_host` with the username and IP address of the target system.

### 3. `install_docker.yml`
This is the main playbook that includes tasks from separate files:
```yaml
---
- name: Install Docker on Pop!_OS
  hosts: pop_os
  become: true

  tasks:
    - name: Include prerequisites
      include_tasks: tasks/prerequisites.yml

    - name: Install Docker
      include_tasks: tasks/install_docker.yml

    - name: Start and enable Docker service
      include_tasks: tasks/start_services.yml

    - name: Post-installation steps
      include_tasks: tasks/post_install.yml
```

### 4. Task Files
#### a. `tasks/prerequisites.yml`
Update the system and install prerequisite packages:
```yaml
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
```

#### b. `tasks/install_docker.yml`
Install Docker CE using the official Docker repository:
```yaml
---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Install Docker and dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
```

#### c. `tasks/start_services.yml`
Start and enable the Docker service:
```yaml
---
- name: Start Docker service
  service:
    name: docker
    state: started

- name: Enable Docker service
  service:
    name: docker
    enabled: true
```

#### d. `tasks/post_install.yml`
Add the current user to the `docker` group (optional step to avoid using `sudo` for Docker commands):
```yaml
---
- name: Add user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
```

### 5. `group_vars/all.yml`
Variable file for global configuration (optional but can be useful for environment-specific settings):
```yaml
docker_package_version: latest
```

### How to Run the Playbook
Run the following command to execute the playbook:
```bash
ansible-playbook install_docker.yml
```

This structure maintains modularity, makes the playbook reusable, and is aligned with Ansible's best practices. Let me know if you need further assistance!
